# Generated by Django 5.1.3 on 2024-11-16 22:47

import core.uploader.infra.uploader_django_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_key', models.UUIDField(default=uuid.uuid4, help_text='Used to attach the document to another object. Cannot be used to retrieve the document file.', unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, help_text='Used to retrieve the document file itself. Should not be readable until the document is attached to another object.', unique=True)),
                ('file', models.FileField(upload_to=core.uploader.infra.uploader_django_app.models.document_file_path)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('IMG', 'IMG'), ('AVATAR', 'AVATAR')], default='PDF', max_length=6)),
            ],
        ),
    ]
