# Generated by Django 5.1.2 on 2024-10-22 12:02

import core.image.infra.image_django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.image.infra.image_django_app.models.upload_image_fomater)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
