# Generated by Django 5.1.2 on 2024-10-15 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('qty_slots', models.IntegerField(default=0)),
                ('sector_type', models.CharField(choices=[('is_free', 'is_free'), ('is_contract', 'is_contract')], max_length=25)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='parking_django_app.parking')),
            ],
        ),
    ]
