# Generated by Django 5.1.2 on 2024-10-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0003_alter_employee_user'),
        ('parking_django_app', '0002_alter_parkingsector_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='company_django_app.company'),
        ),
    ]
