# Generated by Django 5.1.2 on 2024-10-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0002_parkingsector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsector',
            name='sector_type',
            field=models.CharField(choices=[('ROTATIVE', 'ROTATIVE'), ('CONTRACT', 'CONTRACT')], max_length=8),
        ),
    ]
