# Generated by Django 5.1.2 on 2024-10-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0003_alter_parkingsector_sector_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name_plural': 'parking'},
        ),
        migrations.AlterModelOptions(
            name='parkingsector',
            options={'verbose_name_plural': 'parking_sector'},
        ),
        migrations.AlterModelTable(
            name='parking',
            table='parking',
        ),
        migrations.AlterModelTable(
            name='parkingsector',
            table='parking_sector',
        ),
    ]
