# Generated by Django 5.1.2 on 2024-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0004_alter_parking_options_alter_parkingsector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsector',
            name='contract',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
