# Generated by Django 5.1.2 on 2024-10-17 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0005_parkingsector_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='parking_django_app.parking')),
            ],
        ),
    ]
