# Generated by Django 5.1.2 on 2024-10-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_django_app', '0006_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name_plural': 'operations'},
        ),
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name_plural': 'parkings'},
        ),
        migrations.AlterModelOptions(
            name='parkingsector',
            options={'verbose_name_plural': 'parking_sectors'},
        ),
        migrations.AlterModelTable(
            name='operation',
            table='operation',
        ),
    ]
