# Generated by Django 5.1.2 on 2024-10-23 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader_django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_type', models.CharField(choices=[('PJ', 'PJ'), ('PF', 'PF')], max_length=2)),
                ('document_number', models.CharField(max_length=14, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('system_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('avatar', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader_django_app.document')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_django_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
    ]
