# Generated by Django 5.1.2 on 2024-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
