# Generated by Django 5.1.2 on 2024-10-22 18:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TRANSPORTADORA', 'Transportadora'), ('ARMAZEM', 'Armazem'), ('TERMINAL', 'Terminal')], max_length=255)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_contracts', to='company_django_app.company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_contracts', to='company_django_app.company')),
            ],
            options={
                'verbose_name_plural': 'contracts',
                'db_table': 'contract',
            },
        ),
    ]
