# Generated by Django 5.1.2 on 2024-10-23 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0003_alter_employee_user_packing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
