# Generated by Django 5.1.2 on 2024-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0004_alter_company_document'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='document',
        ),
        migrations.AddField(
            model_name='company',
            name='document',
            field=models.ManyToManyField(blank=True, related_name='company_document', to='uploader.document'),
        ),
    ]
