# Generated by Django 5.1.2 on 2024-10-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '0005_remove_company_document_company_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='document',
            new_name='documents',
        ),
    ]
