# Generated by Django 5.1.2 on 2024-10-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0002_alter_body_options_body_created_at_body_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name_plural': 'bodies'},
        ),
        migrations.AlterModelTable(
            name='body',
            table='body',
        ),
    ]
