# Generated by Django 5.1.2 on 2024-10-28 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0003_alter_body_options_alter_body_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='body',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='body',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='body',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='body',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
