# Generated by Django 5.1.2 on 2024-10-28 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0004_remove_body_created_at_remove_body_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('axle', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'modalities',
                'db_table': 'modality',
            },
        ),
    ]
