# Generated by Django 5.1.2 on 2024-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0005_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='axle',
            field=models.IntegerField(),
        ),
    ]
