# Generated by Django 5.1.2 on 2024-11-01 12:10

import core.vehicle.domain.value_objects
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0006_alter_modality_axle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=10)),
                ('chassis', models.CharField(max_length=45)),
                ('renavam', models.CharField(max_length=45)),
                ('axle', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gross_weight', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('TRACIONADORA', 'Tracionadora'), ('CARRETA', 'Carreta'), ('DOLLY', 'Dolly'), ('MOTO', 'Moto'), ('CARRO', 'Carro'), ('CAMIONETA', 'Camioneta')], default=core.vehicle.domain.value_objects.VehicleType['CARRO'], max_length=45)),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='vehicle_django_app.body')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modality', to='vehicle_django_app.modality')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
