# Generated by Django 5.1.2 on 2024-11-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_django_app', '0001_initial'),
        ('vehicle_django_app', '0008_alter_vehicle_axle_alter_vehicle_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='uploader_django_app.document'),
        ),
    ]
