# Generated by Django 5.1.2 on 2024-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_django_app', '0001_initial'),
        ('vehicle_django_app', '0009_vehicle_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='document',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='document',
            field=models.ManyToManyField(blank=True, null=True, related_name='document', to='uploader_django_app.document'),
        ),
    ]
