# Generated by Django 5.1.2 on 2024-11-03 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_django_app', '0001_initial'),
        ('vehicle_django_app', '0012_remove_vehicle_document_vehicle_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='documents',
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader_django_app.document')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle_django_app.vehicle')),
            ],
            options={
                'verbose_name_plural': 'vehicle_documents',
                'db_table': 'vehicle_document',
                'unique_together': {('vehicle', 'document')},
            },
        ),
    ]
