# Generated by Django 5.1.2 on 2024-11-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0013_remove_vehicle_documents_vehicledocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': 'vehicles'},
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
