# Generated by Django 5.1.2 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_django_app', '0001_initial'),
        ('vehicle_django_app', '0014_alter_vehicle_options_alter_vehicle_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='documents',
            field=models.ManyToManyField(related_name='+', to='uploader_django_app.document'),
        ),
        migrations.DeleteModel(
            name='VehicleDocument',
        ),
    ]
