# Generated by Django 5.1.2 on 2024-11-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0007_composition'),
        ('vehicle_django_app', '0015_vehicle_documents_delete_vehicledocument'),
    ]

    operations = [
    ]
