# Generated by Django 5.1.2 on 2024-11-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_django_app', '0017_alter_composition_options_composition_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name_plural': 'compositions'},
        ),
        migrations.AlterModelTable(
            name='composition',
            table='composition',
        ),
    ]
