# Generated by Django 5.1.2 on 2024-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMG', 'IMG')], default='PDF', max_length=3),
        ),
    ]
