# Generated by Django 5.1.2 on 2024-10-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluator',
        ),
    ]
