# Generated by Django 5.1.2 on 2024-11-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
