# Generated by Django 5.1.2 on 2024-10-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_django_app', '0003_alter_user_options_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='document_number',
            new_name='address',
        ),
    ]
