# Generated by Django 5.1.3 on 2024-11-22 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=70)),
                ('payment_rules', models.JSONField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='parking_django_app.parking')),
            ],
            options={
                'verbose_name_plural': 'services',
                'db_table': 'service',
            },
        ),
    ]
