# Generated by Django 5.1.2 on 2024-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_type', models.CharField(choices=[('PJ', 'PJ'), ('PF', 'PF')], max_length=2)),
                ('document_number', models.CharField(max_length=14, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('system_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
    ]
