# Generated by Django 5.1.2 on 2024-10-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_employee'),
        ('image_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pic',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='image_django_app.imageprofilepic'),
        ),
    ]
