# Generated by Django 5.1.2 on 2024-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='system_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
