# Generated by Django 5.1.2 on 2024-10-24 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_django_app.company')),
            ],
            options={
                'verbose_name_plural': 'measurement units',
                'db_table': 'measurement_unit',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_django_app.company')),
            ],
        ),
    ]
