# Generated by Django 5.1.2 on 2024-10-24 23:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_django_app', '__first__'),
        ('product_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_django_app.company')),
            ],
            options={
                'verbose_name_plural': 'measurement units',
                'db_table': 'measurement_unit',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_django_app.company')),
            ],
            options={
                'verbose_name_plural': 'packings',
                'db_table': 'packing',
            },
        ),
        migrations.CreateModel(
            name='PurchaseSaleOrder',
            fields=[
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('operation_terminal_id', models.IntegerField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('CARGA', 'Carga'), ('DESCARGA', 'Descarga')], max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='company_django_app.company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_django_app.company')),
                ('mesaruement_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_django_app.measurementunit')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_django_app.packing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_django_app.product')),
            ],
            options={
                'verbose_name_plural': 'purchase_sale_orders',
                'db_table': 'purchase_sale_order',
            },
        ),
    ]
