# Generated by Django 5.1.2 on 2024-10-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_django_app', '__first__'),
        ('order_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesaleorder',
            name='operation_terminal_id',
        ),
        migrations.AddField(
            model_name='purchasesaleorder',
            name='operation_terminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operation_terminal_orders', to='company_django_app.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasesaleorder',
            name='mesaruement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_django_app.measurementunit'),
        ),
        migrations.AlterField(
            model_name='purchasesaleorder',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_orders', to='order_django_app.packing'),
        ),
    ]
