# Generated by Django 5.1.2 on 2024-10-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcontract',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transportcontract',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
