# Generated by Django 5.1.2 on 2024-10-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0002_remove_purchasesaleorder_operation_terminal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesaleorder',
            name='mesaruement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesaruement_unit_orders', to='order_django_app.measurementunit'),
        ),
    ]
