# Generated by Django 5.1.3 on 2024-11-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0002_trip'),
        ('user_django_app', '0001_initial'),
        ('vehicle_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_trips', to='user_django_app.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_trips', to='vehicle_django_app.composition'),
        ),
    ]
