# Generated by Django 5.1.2 on 2024-10-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0003_alter_purchasesaleorder_mesaruement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesaleorder',
            name='mesaruement_unit',
        ),
        migrations.AddField(
            model_name='purchasesaleorder',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_unit_orders', to='order_django_app.measurementunit'),
        ),
    ]
