# Generated by Django 5.1.3 on 2024-11-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0003_alter_trip_driver_alter_trip_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transport_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='order_django_app.transportcontract'),
        ),
    ]
