# Generated by Django 5.1.3 on 2024-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0004_alter_trip_transport_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
