# Generated by Django 5.1.3 on 2024-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_django_app', '0005_alter_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesaleorder',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasesaleorder',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='transportcontract',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='transportcontract',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
