# Generated by Django 5.1.2 on 2024-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
