import uuid

bodies_data = [
    {"description": "Baú", "id": "d77b81f3-8eaa-4b08-a8f4-a60524a3d40f"},
    {"description": "Carroceria Aberta", "id": "fea18fde-8c59-4e13-8dec-c3d9b866a74e"},
    {"description": "Sider", "id": "9ab9f166-2a19-4887-aae8-ff27c9aeacf7"},
    {"description": "Graneleiro", "id": "c326d1be-d9b0-4437-826a-6fbc4c036736"},
    {"description": "Porta-Container", "id": "5d611c2b-9693-47ba-9a42-09c7014c9d66"},
]


modalities_data = [
    {"id": uuid.uuid4(), "description": "Caminhão 2 eixos", "axle": "2"},
    {"id": uuid.uuid4(), "description": "Caminhão 3 eixos", "axle": "3"},
    {"id": uuid.uuid4(), "description": "Caminhão Toco", "axle": "2"},
    {"id": uuid.uuid4(), "description": "Caminhão Truck", "axle": "3"},
    {
        "id": uuid.uuid4(),
        "description": "Carreta Cavalo Mecânico 2 eixos",
        "axle": "4",
    },
    {
        "id": uuid.uuid4(),
        "description": "Carreta Cavalo Mecânico 3 eixos",
        "axle": "5",
    },
    {"id": uuid.uuid4(), "description": "Carreta Bitrem", "axle": "7"},
    {"id": uuid.uuid4(), "description": "Carreta Rodotrem", "axle": "9"},
    {"id": uuid.uuid4(), "description": "Caminhão Munck", "axle": "4"},
    {"id": uuid.uuid4(), "description": "Caminhão Baú", "axle": "3"},
]

vehicles_data = [
    {
        "id": uuid.uuid4(),
        "license": "ABC1234",
        "chassis": "CHASSIS123",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2010,
        "gross_weight": 15000,
        "vehicle_type": "Carreta",
        "body": None,
        "modality": None,
    },
    {
        "id": uuid.uuid4(),
        "license": "DEF5678",
        "chassis": "CHASSIS1234",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2021,
        "gross_weight": 15000,
        "vehicle_type": "Dolly",
        "body": None,
        "modality": None,
    },
    {
        "id": uuid.uuid4(),
        "license": "GHI9101",
        "chassis": "CHASSIS12345",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2012,
        "gross_weight": 15000,
        "vehicle_type": "Tracionadora",
        "body": None,
        "modality": None,
    },
    {
        "id": uuid.uuid4(),
        "license": "JKL1121",
        "chassis": "CHASSIS123456",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2013,
        "gross_weight": 15000,
        "vehicle_type": "Moto",
        "body": None,
        "modality": None,
    },
    {
        "id": uuid.uuid4(),
        "license": "MNO3141",
        "chassis": "CHASSIS1234567",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2022,
        "gross_weight": 15000,
        "vehicle_type": "Carro",
        "body": None,
        "modality": None,
    },
    {
        "id": uuid.uuid4(),
        "license": "PQR5161",
        "chassis": "CHASSIS12345678",
        "renavam": "RENAVAM123",
        "axle": 4,
        "year": 2024,
        "gross_weight": 15000,
        "vehicle_type": "Camioneta",
        "body": None,
        "modality": None,
    },
]
